//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G7PVFAPPLATEST25.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public string VendorID { get; set; }
        public string MaterialID { get; set; }
        public string SupplyUnitPrice { get; set; }
    
        public virtual Rawmaterial Rawmaterial { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
