//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G7PVFAPPLATEST25.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing
    {
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPostalCode { get; set; }
        public string OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderedQuantity { get; set; }
        public string ProductID { get; set; }
        public string ProductDescription { get; set; }
        public string ProductFinish { get; set; }
        public string ProductStandardPrice { get; set; }
        public string ProductLineName { get; set; }
    }
}
