//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G7PVFAPPLATEST25.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplierdetail
    {
        public string ProductID { get; set; }
        public string ProductDescription { get; set; }
        public string MaterialName { get; set; }
        public string VendorName { get; set; }
        public string VendorAddress { get; set; }
    }
}
