//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G7PVFAPPLATEST25.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesperson
    {
        public string SalespersonID { get; set; }
        public string SalespersonName { get; set; }
        public string SalespersonTelephone { get; set; }
        public string SalespersonFax { get; set; }
        public string TerritoryID { get; set; }
    
        public virtual Territory Territory { get; set; }
    }
}
